### ISSUE TITLE
[BREAKING] New NT syscall introduced with minor Win10 update

### ISSUE THREAD

**Issue by w3lld0ne** [hfiref0x/SyscallTables#3]
Update KB5025221 for Win10 19045 (maybe 19041/19042+) inserts NtCopyFileChunk at index 0xA3 and each higher syscall is changed too as a result.

**Comment by hfiref0x** [comment]
Interesting indeed. They did this before with NtLoadKey3 too. I will update tables for 1904x W10 variants.

**Comment by l41urie** [comment]
It occurs to me that this only updates version 19041, But there's more that are affected.

We shall have barbecue in Redmond and throw whoever is responsible for this pile of garbage right on top.
